-- MySQL Script generated by MySQL Workbench
-- Čt 26. prosince 2019, 13:10:44 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USERS` (
  `user_id` INT(6) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORY` (
  `category_id` INT(2) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REGION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REGION` (
  `region_id` INT(2) NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`region_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ITEM` (
  `item_id` INT(5) NOT NULL,
  `publication_date` DATETIME NOT NULL,
  `modification_date` DATETIME NULL,
  `price` INT(7) NOT NULL,
  `USERS_user_id` INT(6) NOT NULL,
  `CATEGORY_category_id` INT(2) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `REGION_region_id` INT(2) NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_ITEM_USERS1_idx` (`USERS_user_id` ASC) VISIBLE,
  INDEX `fk_ITEM_CATEGORY1_idx` (`CATEGORY_category_id` ASC) VISIBLE,
  INDEX `fk_ITEM_REGION1_idx` (`REGION_region_id` ASC) VISIBLE,
  CONSTRAINT `fk_ITEM_USERS1`
    FOREIGN KEY (`USERS_user_id`)
    REFERENCES `mydb`.`USERS` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEM_CATEGORY1`
    FOREIGN KEY (`CATEGORY_category_id`)
    REFERENCES `mydb`.`CATEGORY` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEM_REGION1`
    FOREIGN KEY (`REGION_region_id`)
    REFERENCES `mydb`.`REGION` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITEM_COMMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ITEM_COMMENT` (
  `i_comment_id` INT(6) NOT NULL,
  `comment` TEXT NOT NULL,
  `ITEM_item_id` INT(5) NOT NULL,
  `publication_date` DATETIME NOT NULL,
  `USERS_user_id` INT(6) NOT NULL,
  PRIMARY KEY (`i_comment_id`),
  INDEX `fk_ITEM_COMMENT_ITEM1_idx` (`ITEM_item_id` ASC) VISIBLE,
  INDEX `fk_ITEM_COMMENT_USERS1_idx` (`USERS_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_ITEM_COMMENT_ITEM1`
    FOREIGN KEY (`ITEM_item_id`)
    REFERENCES `mydb`.`ITEM` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEM_COMMENT_USERS1`
    FOREIGN KEY (`USERS_user_id`)
    REFERENCES `mydb`.`USERS` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CITY` (
  `city_id` INT(5) NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  `ITEM_LOCATION_i_location_id` INT(3) NOT NULL,
  `ITEM_LOCATION_ITEM_item_id` INT(5) NOT NULL,
  `REGION_region_id` INT(2) NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_CITY_REGION1_idx` (`REGION_region_id` ASC) VISIBLE,
  CONSTRAINT `fk_CITY_REGION1`
    FOREIGN KEY (`REGION_region_id`)
    REFERENCES `mydb`.`REGION` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RATING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RATING` (
  `rating_id` INT(5) NOT NULL,
  `content` TEXT NOT NULL,
  `ITEM_item_id` INT(5) NOT NULL,
  PRIMARY KEY (`rating_id`),
  INDEX `fk_RATING_ITEM1_idx` (`ITEM_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_RATING_ITEM1`
    FOREIGN KEY (`ITEM_item_id`)
    REFERENCES `mydb`.`ITEM` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
