-- MySQL Script generated by MySQL Workbench
-- So 28. prosince 2019, 11:31:59 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_dev` ;
USE `db_dev` ;

-- -----------------------------------------------------
-- Table `db_dev`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dev`.`users` (
                                                `user_id` INT(6) NOT NULL AUTO_INCREMENT,
                                                `username` VARCHAR(45) NOT NULL,
                                                `password` VARCHAR(45) NOT NULL,
                                                `email` VARCHAR(45) NOT NULL,
                                                `created` DATETIME NOT NULL,
                                                `description` TEXT NOT NULL,
                                                `role` VARCHAR(15) NOT NULL,
                                                PRIMARY KEY (`user_id`))
    ENGINE = InnoDB;

INSERT INTO `users` (`user_id`, `role`, `username`, `email`, `password`, `created`, `description`) VALUES
(NULL, 'admin', 'admin', 'admin@admin.cz', '21232f297a57a5a743894a0e4a801fc3', '2019-12-28 11-59-36', 'administrátor webu'),
(NULL, 'spravce', 'spravce', 'spravce@spravce.cz', '192a2929e714275bee587d280d596eeb', '2019-12-28 11-59-40', 'správce webu'),
(NULL, 'inzerent', 'prvni', 'prvni@gmail.com', '3926efd781f7d330f3779b43426d2cf7', '2019-12-28 11-59-45', 'popis uživatele');
-- -----------------------------------------------------
-- Table `db_dev`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dev`.`categories` (
                                                     `category_id` INT(2) NOT NULL AUTO_INCREMENT,
                                                     `name` VARCHAR(50) NOT NULL,
                                                     PRIMARY KEY (`category_id`))
    ENGINE = InnoDB;

INSERT INTO `categories` (`category_id`, `name`) VALUES
(NULL, 'Byt'),
(NULL, 'Dům'),
(NULL, 'Pozemek');
-- -----------------------------------------------------
-- Table `db_dev`.`regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dev`.`regions` (
                                                  `region_id` INT(2) NOT NULL AUTO_INCREMENT,
                                                  `name` VARCHAR(75) NOT NULL,
                                                  PRIMARY KEY (`region_id`))
    ENGINE = InnoDB;

INSERT INTO `regions` (`region_id`, `name`) VALUES
(NULL, 'Celá ČR'),
(NULL, 'Pardubický kraj'),
(NULL, 'Liberecký kraj');
-- -----------------------------------------------------
-- Table `db_dev`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dev`.`rooms` (
                                                `room_id` INT(2) NOT NULL AUTO_INCREMENT,
                                                `name` VARCHAR(10) NOT NULL,
                                                PRIMARY KEY (`room_id`))
    ENGINE = InnoDB;

INSERT INTO `rooms` (`room_id`, `name`) VALUES
(NULL, '1+kk'),
(NULL, '1+1'),
(NULL, '2+kk'),
(NULL, '2+1'),
(NULL, '3+kk'),
(NULL, '3+1');
-- -----------------------------------------------------
-- Table `db_dev`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dev`.`items` (
                                                `item_id` INT(5) NOT NULL AUTO_INCREMENT,
                                                `publication_date` DATETIME NOT NULL,
                                                `modification_date` DATETIME NULL,
                                                `price` INT(7) NOT NULL,
                                                `users_user_id` INT(6) NOT NULL,
                                                `categories_category_id` INT(2) NOT NULL,
                                                `title` VARCHAR(45) NOT NULL,
                                                `description` TEXT NOT NULL,
                                                `rooms_room_id` INT(2) NOT NULL,
                                                `cities_city_id` INT NOT NULL,
                                                `type` VARCHAR(45) NOT NULL,
                                                PRIMARY KEY (`item_id`),
                                                INDEX `fk_ITEM_USERS1_idx` (`users_user_id` ASC),
                                                INDEX `fk_ITEM_CATEGORY1_idx` (`categories_category_id` ASC),
                                                INDEX `fk_ITEMS_ROOMS1_idx` (`rooms_room_id` ASC),
                                                INDEX `fk_items_cities1_idx` (`cities_city_id` ASC),
                                                CONSTRAINT `fk_ITEM_USERS1`
                                                    FOREIGN KEY (`users_user_id`)
                                                        REFERENCES `db_dev`.`users` (`user_id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
                                                CONSTRAINT `fk_ITEM_CATEGORY1`
                                                    FOREIGN KEY (`categories_category_id`)
                                                        REFERENCES `db_dev`.`categories` (`category_id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
                                                CONSTRAINT `fk_ITEMS_ROOMS1`
                                                    FOREIGN KEY (`rooms_room_id`)
                                                        REFERENCES `db_dev`.`rooms` (`room_id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
                                                CONSTRAINT `fk_items_cities1`
                                                    FOREIGN KEY (`cities_city_id`)
                                                        REFERENCES `db_dev`.`cities` (`city_id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;

INSERT INTO `items` (`item_id`, `publication_date`, `price`, `users_user_id`, `categories_category_id`,
                     `title`, `description`, `cities_city_id`, `rooms_room_id`, `type`) VALUES
(NULL, '2019-12-29 21-03-21', 13500, 1, 1, 'Pronájem luxusního bytu', 'Jedná se o...', 1, 4, 'Pronájem');
-- -----------------------------------------------------
-- Table `db_dev`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dev`.`messages` (
                                                   `message_id` INT(6) NOT NULL AUTO_INCREMENT,
                                                   `message` TEXT NOT NULL,
                                                   `publication_date` DATETIME NOT NULL,
                                                   `USERS_sender_id` INT(6) NOT NULL,
                                                   `USERS_reciever_id1` INT(6) NOT NULL,
                                                   PRIMARY KEY (`message_id`),
                                                   INDEX `fk_ITEM_COMMENT_USERS1_idx` (`USERS_sender_id` ASC),
                                                   INDEX `fk_MESSAGES_USERS1_idx` (`USERS_reciever_id1` ASC),
                                                   CONSTRAINT `fk_ITEM_COMMENT_USERS1`
                                                       FOREIGN KEY (`USERS_sender_id`)
                                                           REFERENCES `db_dev`.`users` (`user_id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_MESSAGES_USERS1`
                                                       FOREIGN KEY (`USERS_reciever_id1`)
                                                           REFERENCES `db_dev`.`users` (`user_id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dev`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dev`.`cities` (
                                                 `city_id` INT NOT NULL AUTO_INCREMENT,
                                                 `name` VARCHAR(45) NOT NULL,
                                                 `regions_region_id` INT NOT NULL,
                                                 PRIMARY KEY (`city_id`),
                                                 INDEX `fk_cities_regions1_idx` (`regions_region_id` ASC),
                                                 CONSTRAINT `fk_cities_regions1`
                                                     FOREIGN KEY (`regions_region_id`)
                                                         REFERENCES `db_dev`.`regions` (`region_id`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION)
    ENGINE = InnoDB;

INSERT INTO `cities` (`city_id`, `name`, `regions_region_id`) VALUES
(NULL, 'Pardubice', 2),
(NULL, 'Chrudim', 2),
(NULL, 'Svitavy', 2);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SELECT * FROM users;

SELECT name FROM regions;

SELECT item_id, publication_date, price, users.username,categories.name AS category,
       title, items.description, cities.name AS city, regions.name AS region, rooms.name AS room, type FROM items
                JOIN users ON items.USERS_user_id=user_id
                JOIN categories ON items.categories_category_id = categories.category_id
                JOIN cities ON items.cities_city_id = cities.city_id
                JOIN regions on cities.regions_region_id = region_id
                JOIN rooms on items.ROOMS_room_id = room_id
ORDER BY publication_date;